# ref: https://github.com/lighttiger2505/.dotfiles/blob/master/.vim/rc/dein_lazy.toml

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
hook_source = 'source ~/.vim/config/plugins/previm.rc.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_source = ['previm/previm']
hook_source = 'source ~/.vim/config/plugins/openbrowser.rc.vim'

[[plugins]]
repo = 'thinca/vim-showtime'
on_ft = ['markdown']

[[plugins]]
repo = 'thinca/vim-themis'
on_ft = ['vim']

