# ref: https://github.com/lighttiger2505/.dotfiles/blob/master/.vim/rc/dein_lsp.toml

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
#if = "!has('nvim')"
#on_ft = ['python', 'go', 'typescript', 'c', 'cpp']
hook_source = 'source ~/.vim/config/plugins/lsp.rc.vim'

[[plugins]]
repo = 'ryanolsonx/vim-lsp-typescript'
depends = ['vim-lsp']
on_ft = ['typescript']

[[plugins]]
repo = 'ryanolsonx/vim-lsp-swift'
depends = ['vim-lsp']
on_ft = ['swift']

