# ref: https://oki2a24.com/2020/07/01/coloscheme-settings-in-only-dein-vim-toml-file/

#[[plugins]]
#repo = 'altercation/vim-colors-solarized'
#hook_add = '''
#  source ~/.vim/config/plugins/solarized.rc.vim
#  set background=light
#  autocmd VimEnter * ++nested colorscheme solarized
#  call togglebg#map('<F5>')
#'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  set background=dark
  autocmd VimEnter * ++nested colorscheme iceberg
'''

[[plugins]]
repo = 'arcticicestudio/nord-vim'
#hook_add = '''
#  set background=dark
#  autocmd VimEnter * ++nested colorscheme nord
#'''

