# ref: https://github.com/Shougo/shougo-s-github/blob/959a1069654d90f56bbb8b2f5a5f6d065010d102/vim/rc/ddu.toml

[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
on_source = 'denops.vim'
hook_source = 'source ~/.vim/config/plugins/ddu.rc.vim'

# UIs

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'

# Sources

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

# Filters

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_hidden'
on_source = 'ddu.vim'

# Kinds

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

# Colmuns

[[plugins]]
repo = 'Shougo/ddu-column-filename'
on_source = 'ddu.vim'
