# ref: https://github.com/lighttiger2505/.dotfiles/blob/master/.vim/rc/dein_complete.toml
#    : https://github.com/lighttiger2505/.dotfiles/blob/master/.vim/rc/dein_lsp.toml

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
depends = ['asyncomplete-buffer.vim',
           'asyncomplete-file.vim',
           'asyncomplete-gocode.vim',
           'asyncomplete-necosyntax.vim',
           'asyncomplete-tags.vim',
           'asyncomplete-necovim.vim',
           'async.vim',
           'asyncomplete-lsp.vim',
           'vim-lsp',
          ]
hook_source = 'source ~/.vim/config/plugins/asyncomplete.rc.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-buffer.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-file.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-gocode.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-necovim.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-necosyntax.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-tags.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
#on_ft = ['python', 'go', 'typescript', 'c', 'cpp']
hook_source = 'source ~/.vim/config/plugins/lsp.rc.vim'

[[plugins]]
repo = 'ryanolsonx/vim-lsp-typescript'
depends = ['vim-lsp']
on_ft = ['typescript']

[[plugins]]
repo = 'ryanolsonx/vim-lsp-swift'
depends = ['vim-lsp']
on_ft = ['swift']

