# ref: https://github.com/lighttiger2505/.dotfiles/blob/073c6c4082248052d34ab5243c6957ebb4611d8f/.vim/rc/dein_lazy.toml

[[plugins]]
repo = 'previm/previm'
depends = ['open-browser.vim']
#on_cmd = ['PrevimOpen']
on_ft = ['markdown']
hook_source = 'source ~/.vim/config/plugins/previm.rc.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = ['<Plug>(openbrowser-smart-search)']
hook_source = 'source ~/.vim/config/plugins/openbrowser.rc.vim'

[[plugins]]
repo = 'thinca/vim-showtime'
on_ft = ['markdown']

[[plugins]]
repo = 'thinca/vim-themis'
on_ft = ['vim']

