# ref: https://github.com/lighttiger2505/.dotfiles/blob/master/.vim/rc/dein_lsp.toml

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = ['vim-lsp-settings']
#on_ft = ['python', 'go', 'typescript', 'c', 'cpp']

[[plugins]]
repo = 'mattn/vim-lsp-settings'

