# ref: https://github.com/lighttiger2505/.dotfiles/blob/master/.vim/rc/dein_lsp.toml

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = ['vim-lsp-settings']
hook_add = 'source ~/.vim/config/plugins/lsp.rc.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

# Not work
[[plugins]]
repo = 'https://git.sr.ht/~whynothugo/lsp_lines.nvim'
if = "has('nvim')"
hook_add = '''
lua <<EOF
  require("lsp_lines").setup()
  vim.diagnostic.config({
    virtual_text = false,
  })
  vim.keymap.set(
    "",
    "<Leader>l",
    require("lsp_lines").toggle,
    { desc = "Toggle lsp_lines" }
  )
EOF
'''
