[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/config/plugins/lightline.rc.vim'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
if = "has('nvim')"
hook_add = '''
  set termguicolors
  autocmd VimEnter * ++nested lua require('colorizer').setup {}
'''

[[plugins]]
repo = 'lilydjwg/colorizer'
if = "!has('nvim')"

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'source ~/.vim/config/plugins/easymotion.rc.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = 'source ~/.vim/config/plugins/vimindentguides.rc.vim'

#[[plugins]]
#repo = 'github/copilot.vim'
#hook_add = '''
#  let g:copilot_no_maps = v:true
#  let g:copilot_hide_during_completion = 0
#  inoremap <script><silent><nowait><expr> <C-g> copilot#Accept()
#'''

[[plugins]]
repo = 'skanehira/translate.vim'
hook_add = 'source ~/.vim/config/plugins/translate.rc.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = 'set helplang=ja,en'

# ref: https://twitter.com/the_uhooi/status/1220296839150260224
[[plugins]]
repo = 'tweekmonster/helpful.vim'

[[plugins]]
repo = 'tpope/vim-characterize'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
if = "has('nvim')"
hook_add = '''
lua <<EOF
  require('gitsigns').setup()
EOF
  source ~/.vim/config/plugins/gitsigns.rc.vim
'''

# Not working in Neovim
#[[plugins]]
#repo = 'mattn/vim-nekokak'
#if = "!has('nvim')"

[[plugins]]
repo = 'delphinus/nekokak.nvim'
if = "has('nvim')"
hook_add = '''
  set termguicolors
  lua require('nekokak').setup {}
'''

[[plugins]]
repo = 'uhooi/uhooi.nvim'
if = "has('nvim')"
hook_add = '''
  set termguicolors
  lua require('uhooi').setup {}
'''

