[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-entire'

[[plugins]]
repo = 'kana/vim-textobj-indent'

[[plugins]]
repo = 'sgur/vim-textobj-parameter'

[[plugins]]
repo = 'thinca/vim-textobj-between'

