[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/config/plugins/lightline.rc.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = 'source ~/.vim/config/plugins/vimindentguides.rc.vim'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'skanehira/translate.vim'
hook_add = 'source ~/.vim/config/plugins/translate.rc.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = 'set helplang=ja,en'

# ref: https://twitter.com/the_uhooi/status/1220296839150260224?s=20
[[plugins]]
repo = 'tweekmonster/helpful.vim'

# Not working in Neovim
#[[plugins]]
#repo = 'mattn/vim-nekokak'

