# ref: https://github.com/lighttiger2505/.dotfiles/blob/073c6c4082248052d34ab5243c6957ebb4611d8f/.vim/rc/dein_syntax.toml

[[plugins]]
repo = 'keith/swift.vim'
on_ft = ['swift']
#hook_source = '''
#  let g:syntastic_swift_checkers = ['swiftpm', 'swiftlint']
#'''

[[plugins]]
repo = 'keith/xcconfig.vim'
on_path = '\.xcconfig$'

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_path = '\.csv$'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_path = ['\.pu$', '\.uml$', '\.plantuml$']

[[plugins]]
repo = 'tokorom/vim-review'
on_ft = ['review']
hook_source = 'source ~/.vim/config/plugins/vimreview.rc.vim'

[[plugins]]
repo = 'kylef/apiblueprint.vim'
on_ft = ['apiblueprint']

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_ft = ['markdown', 'toml', 'help']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

