[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  source ~/.vim/config/plugins/solarized.rc.vim
  set background=light
  autocmd VimEnter * ++nested colorscheme solarized
  call togglebg#map('<F5>')
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
#hook_add = '''
#  set background=dark
#  colorscheme iceberg
#```

[[plugins]]
repo = 'arcticicestudio/nord-vim'
#hook_add = '''
#  set background=dark
#  colorscheme nord
#```

