# 参考：https://github.com/lighttiger2505/.dotfiles/blob/master/.vim/rc/dein_complete.toml

###############################################################
# For Vim
###############################################################

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
if = "!has('nvim')"
depends = ['asyncomplete-lsp.vim', 'asyncomplete-buffer.vim']

[[plugins]]
repo = 'prabirshrestha/asyncomplete-buffer.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

###############################################################
# For NeoVim
###############################################################

[[plugins]]
repo = 'Shougo/deoplete.nvim'
build = ':UpdateRemotePlugins'
if = "has('nvim')"
on_event = 'InsertEnter'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''
#hook_source = 'source ~/.vim/config/plugins/deoplete.rc.vim'

[[plugins]]
repo = 'deoplete-plugins/deoplete-go'
build = 'make'
if = "has('nvim')"
on_ft = ['go']
on_event = 'InsertEnter'
depends = ['deoplete.nvim']
hook_source = '''
  let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

#[[plugins]]
#repo = 'Shougo/neosnippet.vim'
#depends = ['neosnippet-snippets']
#hook_source = 'source ~/.vim/config/plugins/neosnippet.rc.vim'
#
#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'
#
#[[plugins]]
#repo = 'zchee/deoplete-zsh'
#if = "has('nvim')"
#on_ft = ['zsh']
#depends = ['deoplete.nvim']
#
#[[plugins]]
#repo = 'Shougo/neco-vim'
#if = "has('nvim')"
#on_ft = ['vim']
#depends = ['deoplete.nvim']
#
#[[plugins]]
#repo = 'ujihisa/neco-look'
#if = "has('nvim')"
#on_ft = ['gitcommit', 'markdown']
#depends = ['deoplete.nvim']

